### ISSUE TITLE
Missing platform osx-arm64

### ISSUE THREAD

**Issue by dennis-wey** [conda-forge/granian-feedstock#30]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Seems for the package granian there is no osx-arm64 build. Would it be possible to add this?
The other ones like "granian-with-all" are noarch but require granian. So I wonder if you could add this platform in your build process.

### Installed packages

No env needed

### Environment info

No env needed

**Comment by bollwyvl** [comment]
Will take a look, but as someone who doesn't have said machine, i won't be able to test it locally.

For future reference, you can help these things along by submitting feedstock names to https://github.com/conda-forge/conda-forge-pinning-feedstock/pulls?q=is%3Apr+osx-arm64+is%3Aclosed

This ensures all dependency feedstocks are also migrated.

Of particular note, even if we get this through, this will likely not work with #11 until there are native `osx-arm64` runners available.

**Comment by bollwyvl** [comment]
Within the hour after the build from #31 (https://github.com/conda-forge/granian-feedstock/runs/32737693537), should be installable. Please open a new issue with any findings.

**Comment by dennis-wey** [comment]
HI @bollwyvl thanks for the quick response. I can confirm that it works now.
Thanks! Next time I will use the official way
